version: '3.9'

volumes:
  postgres_data:
  static_volume:

services:
  backend:
    build: .
    command: sh ./commands.sh
    volumes:
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/var/logs
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/home/app/web/static
    depends_on:
      - backend
